name: caddy

services:
  caddy:
    container_name: caddy
    image: caddy:${CADDY_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CADDY_FILE_PATH:-./Caddyfile}:/etc/caddy/Caddyfile
      - ./caddy-data:/data/caddy
